# Generated by Django 4.2 on 2024-07-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'рассылка (текст)',
                'verbose_name_plural': 'рассылки (текст)',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
                ('days', models.PositiveIntegerField(verbose_name='Периодичность в днях')),
            ],
            options={
                'verbose_name': 'период',
                'verbose_name_plural': 'периоды',
            },
        ),
        migrations.CreateModel(
            name='StatusAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'статус попытки',
                'verbose_name_plural': 'статусы попыток',
            },
        ),
        migrations.CreateModel(
            name='StatusMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Название')),
            ],
            options={
                'verbose_name': 'статус рассылки',
                'verbose_name_plural': 'статусы рассылок',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sent_datetime', models.DateTimeField(verbose_name='дата и время первой отправки')),
                ('period', models.CharField(max_length=150, verbose_name='периодичность')),
                ('clients', models.ManyToManyField(to='mailing.client')),
                ('mailing_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingtext', verbose_name='Текст рассылки')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.statusmailing', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'рассылка (настройки)',
                'verbose_name_plural': 'рассылки (настройки)',
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_datetime', models.DateTimeField(verbose_name='дата и время попытки')),
                ('server_reply', models.TextField(verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailingsettings', verbose_name='Настройка рассылки')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.statusattempt', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'рассылка (попытка)',
                'verbose_name_plural': 'рассылки (попытки)',
            },
        ),
    ]
