# Generated by Django 4.2 on 2024-07-08 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_client_owner_mailingsettings_owner_mailingtext_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsettings',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.period', verbose_name='периодичность'),
        ),
    ]
