# Generated by Django 4.2 on 2024-07-10 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingsettings_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingattempt',
            name='sent_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='server_reply',
            field=models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.CharField(choices=[('Успешно', 'Успешно'), ('Неуспешно', 'Неуспешно')], default=django.utils.timezone.now, max_length=50, verbose_name='Cтатус рассылки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='period',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', max_length=150, verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='mailingsettings',
            name='status',
            field=models.CharField(choices=[('Завершена', 'Завершена'), ('Создана', 'Создана'), ('Запущена', 'Запущена')], default='Создана', max_length=150, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='StatusAttempt',
        ),
        migrations.DeleteModel(
            name='StatusMailing',
        ),
    ]
