# Generated by Django 4.2 on 2024-07-12 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailingattempt_sent_datetime_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsettings',
            options={'permissions': [('deactivate_mailing', 'Can deactivate mailing'), ('view_all_mailings', 'Can view all mailings')], 'verbose_name': 'рассылка (настройки)', 'verbose_name_plural': 'рассылки (настройки)'},
        ),
    ]
